# Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

# Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_wheel_left_0
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_wheel_left_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController 
    joint: joint_wheel_left_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_wheel_right_0
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_wheel_right_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_wheel_right_2
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint_wheel_left_0
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint_wheel_left_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointEffortController 
    joint: joint_wheel_left_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint_wheel_right_0
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint_wheel_right_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint_wheel_right_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
